#!/bin/sh

VENDOR=hisense
DEVICE=AD686G
OUTDIR=vendor/$VENDOR/$DEVICE

(cat << EOF) > ../../../$OUTDIR/$DEVICE-vendor-blobs.mk
# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
# -------------------------------------------------------------------
# PREBUILT LIBRARIES THAT ARE NEEDED TO BUILD OPEN-SOURCE LIBRARIES -
# -------------------------------------------------------------------
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
######################    DEPENDENCY SECTION  #######################
#PRODUCT_COPY_FILES += \\
#    $OUTDIR/proprietary/system/lib/libril.so:obj/lib/libril.so \\
#    $OUTDIR/proprietary/system/lib/libmmipl.so:obj/lib/libmmipl.so \\
#    $OUTDIR/proprietary/system/lib/libmmjpeg.so:obj/lib/libmmjpeg.so \\
#    $OUTDIR/proprietary/system/lib/liboemcamera.so:obj/lib/liboemcamera.so

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
###################### DON'T EDIT ###################################
PRODUCT_COPY_FILES += \\
EOF
LINEEND=" \\"
COUNT=`cat proprietary-files.txt | grep -v ^# | grep -v ^$ | wc -l | awk {'print $1'}`
for FILE in `cat proprietary-files.txt | grep -v ^# | grep -v ^$`; do
    COUNT=`expr $COUNT - 1`
    if [ $COUNT = "0" ]; then
        LINEEND=""
    fi
    echo "    $OUTDIR/proprietary$FILE:$FILE$LINEEND" >> ../../../$OUTDIR/$DEVICE-vendor-blobs.mk
done
(cat << EOF) > ../../../$OUTDIR/BoardConfigVendor.mk
# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
USE_CAMERA_STUB := false
#PRODUCT_COPY_FILES += \\
#    $OUTDIR/proprietary/charger:root/charger \\
#    $OUTDIR/proprietary/init:root/init \\
#    $OUTDIR/proprietary/system/lib/liboemcamera.so:/system/lib/liboemcamera.so \\
#    $OUTDIR/proprietary/system/lib/libcamera_client.so:/system/lib/libcamera_client.so \\
#    $OUTDIR/proprietary/system/lib/libcameraservice.so:/system/lib/libcameraservice.so
EOF
